# Generated by Django 2.1.7 on 2019-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('works_from', models.IntegerField()),
                ('works_to', models.IntegerField()),
                ('specialisation', models.CharField(max_length=255)),
            ],
        ),
    ]
