# Generated by Django 2.1.7 on 2019-03-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('symptoms', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equeue.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equeue.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient',
            field=models.ManyToManyField(related_name='patient', through='equeue.PatientDoctorRelation', to='equeue.Patient'),
        ),
    ]
