# Generated by Django 2.1.7 on 2019-03-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equeue', '0003_auto_20190330_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctorrelation',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
